### ISSUE TITLE
NPN to Daymet location matching issue

### ISSUE THREAD

**Issue by LucienFitzpatrick** [MortonArb-ForestEcology/Phenology_Forecasting#3]
In our Organize_Data_NPN.R script we currently have an issue with matching the latitude and longitude of NPN and daymet data. Our daymet data is pulled directly from the list of lat and long we get from the NPN data csv. After those lat and long values are read into the daymetr package, they are rounded to only have 5 digits after the decimal whereas the NPN data still has 6 digits. This means the old methodology of creating a "Location" value combining Latitude and Longitude and matching identical values doesn't work. If you round both side than they also won't match as usually 1 value (will be rounded different". So currently we round both sides, then round both sides again, and then they will match. This is functional but very messy.

**Comment by crollinson** [comment]
One potential workaround may be to use a site identifier (name; code) etc. to align datasets and in any sort of merge to use the NPN/input coordinates rather than those that Daymet returns.

**Comment by LucienFitzpatrick** [comment]
For my initial testing I tried using a modifier to specify the precision of the NPN lat and long data as it is exported to a csv so it can be read by daymet. Increasing this precision didn't help which means that the loss of precision occurs when the data is read in, not when it is exported to a csv. 

I also tried using the %like% pipe from the data.table package but that would only work for lat and long separately which ends up being messier than our current work around

While doing diagnostics since the standard data.frame presentations or summaries only show a certain number of digits so you will need to specifiy with "digits = x"

**Comment by crollinson** [comment]
I made a fix in the script for the REU project.  Basically, I get rid of the double-nested list, make it flat, add in site & coord info from the points data frame, and then use lapply to do the GDD calculation.  I then flatten it and save it as a csv.  See [final file](https://github.com/MortonArb-ForestEcology/REU2020-MODIS_phenology/blob/master/scripts/02_Met_data_transform.R) and specifically [this commit ](https://github.com/MortonArb-ForestEcology/REU2020-MODIS_phenology/commit/9cb7fe0cc3b53e54110265d54a3e86206bd143c3#diff-b85281a367a0fe0b09ce53d07bae6f47).

I won't close this issue until these changes have been brought into the forecasting workflow.
